### ISSUE TITLE
How to deal with expired tokens?

### ISSUE THREAD

**Issue by 0x80** [jerelmiller/redux-simple-auth#12]
I didn't find any mention in the docs. What happens when the token expires and can the middleware facilitate the refresh in any way?

**Comment by jerelmiller** [comment]
Hey @0x80. Thanks for your interest in the project!

When the application boots up, it will call your authenticator's `restore` function. If that rejects the promise, it dispatches a restore failed action. This will change the state in the same way the `invalidateSession()` action does (sets `isAuthenticated` to `false`, clears any data, etc).

Depending on your use case, the best way to handle this is to either rerender based on the session state, or if you need more control, listen for the restore failed action. You _should_ be able to do this by importing the `RESTORE_FAILED` action from `redux-simple-auth/actionTypes` (untested).

As far as a token expiring without a refresh of the page, there is currently no support. I do have plans to better integrate with libraries such as React Router, but right now the library is fairly basic. Unfortunately I've been so busy the last couple months, I haven't been able to add more examples or integrations quite yet. 

If you have any ideas or thoughts on how to better facilitate this, let me know! I'm still very open to ideas since the library is fairly young.

**Comment by jerelmiller** [comment]
@0x80 I've made a few updates in the last month or so and updated more of the documentation. Take a look and let me know if any of the updates are useful for you. I'm going to close this issue for now, but feel free to reopen if you feel I haven't been able to better answer your question.

**Comment by 0x80** [comment]
Hi @jerelmiller, thanks for your feedback and continued work on this! At the time I was working on a prototype and eventually authentication didn't even make it into the project sprints. For me this is not relevant anymore at the moment but I'll revisit when I have to implement authentication again.

Cheers!
