### ISSUE TITLE
What data is sent to restore?

### ISSUE THREAD

**Issue by anlauren** [jerelmiller/redux-simple-auth#18]
Hi,
I Have the following problem:
- I invalidate the session
- I log the cookies: not authenticated, the state isn't either
- I redirect to an other page
- I arrive on the other page
There starts the weird behavior:
-> It sends a restore (why? this is not a refresh it's a browserHistory.push (reactRouter)?)
-> The restore actually gets the data from before and I still logged in
---
Hence my question: Where is the data sent to Restore from? I checked, everything was cleared from the session after the invalidate, But I still get the use back

Thanks

**Comment by jerelmiller** [comment]
Hey @anlauren! Apologies I've got a couple busy days ahead of me.

By chance do you have this up somewhere that I could take a look or a sample app that reproduces this behavior?

I'll do my best to answer your questions here in the next couple days. Just wanted you to know I won't forget about this issue!

**Comment by anlauren** [comment]
That was just to see if you had that on top of your head, I don't have a simple example but I'll let you know when I find what is wrong.

On my last investigations, I saw that usually after a reload of a page it sends *redux-simple-auth/RESTORE* and calls previously the custom *restore* function of the storage device.

But when I do a browserHistory.push there, I see the  *redux-simple-auth/RESTORE* event but the *restore* function is not called.
I will try to find why, It might be a problem on my side.
![screen shot 2017-09-13 at 09 15 15](https://user-images.githubusercontent.com/7627816/30366960-cefe74e6-9864-11e7-88a0-b3860e73bfc1.png)
![screen shot 2017-09-13 at 09 14 53](https://user-images.githubusercontent.com/7627816/30367130-40d4c8a4-9865-11e7-8975-8e9dd2ea8a44.png)

**Comment by anlauren** [comment]
Here is the timeline I described in the previous post:

![screen shot 2017-09-13 at 12 05 14](https://user-images.githubusercontent.com/7627816/30374203-fd1a2e30-987b-11e7-9adc-d0895e8ff116.png)

**Comment by jerelmiller** [comment]
Thanks for the detail. I should have some time later today to answer in detail to explain the process. This definitely helps me understand what you are seeing.

**Comment by anlauren** [comment]
Thanks!
That beeing said, I am still unsure if this comes from the simple auth or if my app is triggering double actions, so don't spend to much time on it if you have to many things to do :)

**Comment by jerelmiller** [comment]
So here is the flow of data from the library. A lot of the "magic" comes from the middleware.

https://github.com/jerelmiller/redux-simple-auth/blob/master/src/middleware.js#L63-L74

If you take a look here, you'll notice that it calls `storage.restore()` as soon as the store has been created. The idea is that upon app boot, we should be able to query the storage device for its data and do stuff with it. `storage` comes from the middleware config. You'll notice that if its not specified, it will use the default storage implementation (the adaptive store). I don't suspect this is your issue since it sounds like your custom storage implementation is being used properly in other contexts.

The next interesting piece you'll see here is that it asks the authenticator to restore the data. This serves as a hook that will allow your app to validate whatever is in the storage device as something that is still considered valid. Assuming it is valid (the promise was resolved), we then dispatch the `restore` action with the data contained in the storage device.

Session invalidation is a combination of a couple things: the reducer and the middleware. The reducer clears out the data and sets `isAuthenticated` to false (behavior you are already seeing). The middleware "watches" every action that flows through redux and checks to see if the session data changes as a result of a call to the action. If so, it will persist to the storage. You can see this behavior here:

https://github.com/jerelmiller/redux-simple-auth/blob/master/src/middleware.js#L116-L123

There is another interesting thing to note here, and I don't think its something I mention in the docs, but when you use `fetch` from `redux-simple-auth`, there is actually a built-in check that verifies the response. If the response comes back with a `401`, it will **automatically dispatch an invalidation**. You can find this code here:

https://github.com/jerelmiller/redux-simple-auth/blob/master/src/middleware.js#L107-L113

This is something I should absolutely document. I suspect this could be surprising behavior.

With all that said, those are the only places I know of that invalidate or restore the session behind the scenes. `storage.restore()` _should_ only happen when the store is created.

Without knowing what the rest of your app looks like, does any of this lend any useful information that you might be able to use to debug? Its also very likely I missed an edge case somewhere.

I just want to conclude by saying, thanks for using this library! I hope its making your life at least a little bit easier :) I'd definitely love to improve it in any way possible.

**Comment by jerelmiller** [comment]
Hey @anlauren. I'm going to close this for now since its been inactive for a while. If you have any more questions, don't hesitate to reopen the issue!
