### ISSUE TITLE
Unable to send token

### ISSUE THREAD

**Issue by cyberwombat** [jerelmiller/redux-simple-auth#58]
So my setup is:
```
const credentialsAuthenticator = createCredentialsAuthenticator({
  endpoint: '/api/auth/login'
})

const localStorageStore = createLocalStorageStore()

const authMiddleware = createAuthMiddleware({ authenticator: credentialsAuthenticator, authorize: oauth2BearerAuthorizer, storage: localStorageStore })
```
This does not send the token with fetch because my localStorage has `token` but the oauth2BearerAuthorizer code looks for `access_token`.  If I change it to `token` it works.

Did I miss something in my config?

**Comment by jerelmiller** [comment]
Hey @cyberwombat 

The `oauth2BearerAuthorizer` was implemented based on the [Ember Simple Auth implementation](https://github.com/simplabs/ember-simple-auth/blob/1.4.2/addon/authorizers/oauth2-bearer.js#L34-L40) which uses `access_token`. Thats the reason it expects `access_token`.

Since you need `token` as the name, what I'd suggest is not using the `oauth2BearerAuthorizer` and instead use a custom one. The following should be equivalent of the `oauth2BearerAuthorizer` with the appropriate name for your use case.

```
const tokenAuthorizer = (data, block) => {
  if (data.token) {
    header('Authorization', `Bearer ${data.token}`)
  }
}
```

Then just be sure to configure the middleware with this authorizer.

```
const middleware = createAuthMiddleware({ authorize: tokenAuthorizer, ... })
```

Hope that helps!

**Comment by cyberwombat** [comment]
Thanks - That's what I ended up doing. Wouldn't it be a smoother experience to get things to match out of the box though? - maybe check for both access_token and token?

**Comment by jerelmiller** [comment]
The reason I haven't done this is due to the spec:

https://tools.ietf.org/html/rfc6750#section-4

This authorizer is meant for OAuth use cases, so using `access_token` seemed pretty sensible. That being said, it might be nice to have a built-in `bearerTokenAuthorizer` that is pre-configured to look for `token` since thats likely a common use-case. 

I'm definitely open to PRs if you'd like to add another built-in authorizer preconfigured that way. If not, I'll see if I can put something together in the next couple days. Thanks for the feedback!

**Comment by cyberwombat** [comment]
#59
