### ISSUE TITLE
Best place to get user session info

### ISSUE THREAD

**Issue by weyert** [jerelmiller/redux-simple-auth#62]
I am working on this application where an API already exists. You need to call `/login` first which will issue a token. This but works fine. Only now I want to retrieve the user information (e.g. settings) after the user successfully logged in by calling the API `/user/current`. What's the best place to do this?  

I would assume I would need to make a new Authenticator which will first call `/login` and once successfully it will call `/user/current` but what about when we it will restore the session? What's the best way to solve this?

**Comment by jerelmiller** [comment]
Hey @weyert! Apologies for taking so long to reply. I've been on vacation the last couple weeks and have not been paying attention to my notifications.

I guess this really depends on what you want to do. I've found the best way to handle getting current user information is to wait until the session is authenticated, then go fetch the data from the endpoint as soon as you are authenticated. I've found that authenticators aren't really the best place for this since really those are just for getting some kind of credentials so that you can authenticate future requests. I'd put the `/user/current` request as a "future" request in this example.

Assuming you have an authenticator that calls the `/login` and gets you your token, this is going to set the `isAuthenticated` flag inside the redux store. You can use this as a mechanism to determine when to fetch the the `/user/current` data.

Here is an example using React and `react-redux`. Feel free to translate this to your framework of choice if you are using this outside of React.

```js
import React from 'react'
import { fetch, getIsAuthenticated } from 'redux-simple-auth'
import { connect } from 'react-redux'

class CurrentUser extends React.Component {
  componentDidUpdate(prevProps) {
    if (!prevProps.isAuthenticated && this.props.isAuthenticated) {
      this.props.dispatch(fetch('/users/current'))
        .then(response => response.json())
        .then(currentUser => {
          /* do something interesting to current user like save it in your redux store */
          this.props.dispatch(/* your redux action */)
        })
    }
  }  

  render() {
    // ...
  }
}

const mapStateToProps = state => ({
  isAuthenticated: getIsAuthenticated(state)
})

export default connect(mapStateToProps)(CurrentUser)
```

Note this is not the only way, but just the way I typically set this up. Feel free to play around with this until you are happy with a solution that works for you. I've both set this up by saving `currentUser` in the redux store, or even setting `currentUser` in local state and using [render props](https://reactjs.org/docs/render-props.html) to obtain user data.

Really my only suggestion with this whole thing is to avoid using authenticators to fetch current user data since they aren't really designed for that sort of thing.

I'd love to hear how you end up solving this if you don't mind sharing!
