### ISSUE TITLE
Remembering session

### ISSUE THREAD

**Issue by weyert** [jerelmiller/redux-simple-auth#65]
I was wondering what is the best way to drive the storage adapter based on the user choice? For example, if you have a 'remember login' you might want to use local storage while this option is unchecked you might want to session storage. 

How can I change the storage type that's being used while authenticating? What's the best approach for this?

**Comment by jerelmiller** [comment]
Hey @weyert.

So unfortunately the library doesn't support dynamic storage devices, but you should be able to create your own storage instance that does what you're looking for. Take a look at the [implementing custom store](https://github.com/jerelmiller/redux-simple-auth#implementing-a-custom-session-store) section in the docs.

The storage device is handed the data given to it from the authenticate action. You can use this to determine which storage device you want to use. The only tricky part you will run into is determining how to restore from the storage device used to persist the data since you won't know which storage device was used ahead of time. One idea is to check both storage devices for the key you store this data under to see which exists.

Here is a rough prototype:

```
const dynamicStorage = {
  persist: data => {
    let storage
    if (data.rememberLogin) {
      storage = localStorage
    } else {
      storage = sessionStorage
    }
    
    storage.setItem('my-stuff', JSON.stringify(data))
  },
  restore: () => new Promise((resolve) => {
    const data = [localStorage, sessionStorage]
      .map(storage => storage.getItem('my-stuff'))
      .filter(Boolean)[0]
      
    return JSON.parse(data)
  })
}
```

**Comment by weyert** [comment]
Yes, I have tried this before but the problem is that you can't access the data you have passed to the `authenticate`-action in `persist` so if I pass a `rememberLogin`-flag as shown below. You won't be able to get this flag because it's not available. I don't really want to pass it to the server-side and return it back again only for this case.

```
dispatch(
    authenticate('credentials', {
        username: username,
        password: password,
        remember_me: shouldRemember,
    })
)
```

**Comment by jerelmiller** [comment]
Thats a good point. Currently you'd have to work around it by returning that data as part of the data resolved from the server. You shouldn't need to send it server side, but you would need to return it.

```js
dispatch(authenticate('credentials', { rememberMe: true })

// in your authenticator
const authenticator = createAuthenticator({
  authenticate({ rememberMe, ...data }) => {
    return fetch('/auth', { body: JSON.stringify(data) })
      .then(result => result.json())
      .then(result => ({ rememberMe, ...data }))
  }
})
```

Would this work for you? I agree its not the most elegant, but this should work for your use case since the data returned when resolved will be passed to `persist` for the configured storage device.

**Comment by weyert** [comment]
Hah, didn't think about that. Let me try this out!

**Comment by weyert** [comment]
Made it work, thank you!
